ecouteClient.o: ecouteClient.c ecouteClient.h
main.o: main.c socket.h msgClient.h traitementString.h ecouteClient.h
msgClient.o: msgClient.c msgClient.h traitementString.h
socket.o: socket.c socket.h
traitementString.o: traitementString.c traitementString.h
