ecouteClient.o: ecouteClient.c ecouteClient.h
main.o: main.c socket.h msgClient.h requestProcessing.h ecouteClient.h
msgClient.o: msgClient.c msgClient.h
requestProcessing.o: requestProcessing.c requestProcessing.h
socket.o: socket.c socket.h
